## Carga de datos | 2003 - 2015

From 1934 to 1963, **San Francisco was infamous for housing some of the world's most notorious criminals on the inescapable island of Alcatraz**.

* Today, the city is known more for its tech scene than its criminal past. But, with rising wealth inequality, housing shortages, and a proliferation of expensive digital toys riding BART to work, there is no scarcity of crime in the city by the bay.

From Sunset to *SOMA*, and Marina to Excelsior, this competition's dataset provides nearly 12 years of crime reports from across all of San Francisco's neighborhoods. Given time and location, you must predict the category of crime that occurred.

We're also encouraging you to explore the dataset visually. What can we learn about the city through visualizations like this Top Crimes Map? The top most up-voted scripts from this competition will receive official Kaggle swag as prizes.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st
import altair as alt
from IPython.display import Image

In [2]:
criminal = pd.read_csv("train.csv (1).zip")

In [3]:
criminal["HORA"] = criminal["Dates"].apply(lambda x: str(x[10:]))
criminal["DIA"] = criminal["Dates"].apply(lambda x: int(str(x[8:10])))
criminal["MES"] = criminal["Dates"].map(lambda x: str(x[5:7]))
criminal["AÑO"] = criminal["Dates"].map(lambda x: str(x[:4]))

In [4]:
criminal.Category.unique()

array(['WARRANTS', 'OTHER OFFENSES', 'LARCENY/THEFT', 'VEHICLE THEFT',
       'VANDALISM', 'NON-CRIMINAL', 'ROBBERY', 'ASSAULT', 'WEAPON LAWS',
       'BURGLARY', 'SUSPICIOUS OCC', 'DRUNKENNESS',
       'FORGERY/COUNTERFEITING', 'DRUG/NARCOTIC', 'STOLEN PROPERTY',
       'SECONDARY CODES', 'TRESPASS', 'MISSING PERSON', 'FRAUD',
       'KIDNAPPING', 'RUNAWAY', 'DRIVING UNDER THE INFLUENCE',
       'SEX OFFENSES FORCIBLE', 'PROSTITUTION', 'DISORDERLY CONDUCT',
       'ARSON', 'FAMILY OFFENSES', 'LIQUOR LAWS', 'BRIBERY',
       'EMBEZZLEMENT', 'SUICIDE', 'LOITERING',
       'SEX OFFENSES NON FORCIBLE', 'EXTORTION', 'GAMBLING', 'BAD CHECKS',
       'TREA', 'RECOVERED VEHICLE', 'PORNOGRAPHY/OBSCENE MAT'],
      dtype=object)

In [5]:
#TAREA | INVESTIGAR CÓMO CLASIFICAR LOS DELITOS EN CHICAGO SEGÚN --> (LEVE, MEDIO Y GRAVE)
LEVE = ['WARRANTS', 'OTHER OFFENSES', 'LARCENY/THEFT', 'VEHICLE THEFT',
       'VANDALISM', 'NON-CRIMINAL']
MEDIO = []
GRAVE = []

In [17]:
MILD = ["MILD" if i in LEVE else i for i in criminal.Category]

In [30]:
criminal # Qué tipo de delito es cometido con mayor frecuencia (Analizar la variable Category | bar (cuantitativas), histograma
from collections import Counter

diccionario2 = Counter(criminal.loc[criminal.AÑO == "2015", "Category"])

In [27]:
criminal.AÑO.unique()

array(['2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008',
       '2007', '2006', '2005', '2004', '2003'], dtype=object)

In [51]:
diccionario2
df2 = pd.DataFrame.from_dict(diccionario2, orient = "index").reset_index().rename(columns = {"index": "Accidente", 0: "numero_accidentes_2015"})
df2

                      Accidente  numero_accidentes_2015
0                      WARRANTS                    1189
1                OTHER OFFENSES                    3626
2                 LARCENY/THEFT                    7511
3                 VEHICLE THEFT                    1408
4                     VANDALISM                    1307
5                  NON-CRIMINAL                    3409
6                       ROBBERY                     722
7                       ASSAULT                    2325
8                   WEAPON LAWS                     314
9                      BURGLARY                    1090
10               SUSPICIOUS OCC                     956
11                  DRUNKENNESS                     109
12       FORGERY/COUNTERFEITING                     127
13                DRUG/NARCOTIC                     751
14              STOLEN PROPERTY                     161
15              SECONDARY CODES                     402
16                     TRESPASS                     213
17               MISSING PERSON                     799
18                        FRAUD                     549
19                   KIDNAPPING                      73
20                      RUNAWAY                      26
21  DRIVING UNDER THE INFLUENCE                      60
22        SEX OFFENSES FORCIBLE                     159
23                 PROSTITUTION                      46
24           DISORDERLY CONDUCT                      71
25                        ARSON                      69
26              FAMILY OFFENSES                      11
27                  LIQUOR LAWS                      35
28                      BRIBERY                      15
29                 EMBEZZLEMENT                      19
30                      SUICIDE                       8
31                    LOITERING                       5
32    SEX OFFENSES NON FORCIBLE                       4
33                    EXTORTION                       4
34                     GAMBLING                       6
35                   BAD CHECKS                       4
36                         TREA                       1

In [52]:
criminal

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y,HORA,DIA,MES,AÑO,MILD,SEVERIDAD
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599,23:53:00,13,05,2015,MILD,MILD
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599,23:53:00,13,05,2015,MILD,MILD
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414,23:33:00,13,05,2015,MILD,MILD
3,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,NORTHERN,NONE,1500 Block of LOMBARD ST,-122.426995,37.800873,23:30:00,13,05,2015,MILD,MILD
4,2015-05-13 23:30:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Wednesday,PARK,NONE,100 Block of BRODERICK ST,-122.438738,37.771541,23:30:00,13,05,2015,MILD,MILD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
878044,2003-01-06 00:15:00,ROBBERY,ROBBERY ON THE STREET WITH A GUN,Monday,TARAVAL,NONE,FARALLONES ST / CAPITOL AV,-122.459033,37.714056,00:15:00,6,01,2003,ROBBERY,ROBBERY
878045,2003-01-06 00:01:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Monday,INGLESIDE,NONE,600 Block of EDNA ST,-122.447364,37.731948,00:01:00,6,01,2003,MILD,MILD
878046,2003-01-06 00:01:00,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,Monday,SOUTHERN,NONE,5TH ST / FOLSOM ST,-122.403390,37.780266,00:01:00,6,01,2003,MILD,MILD
878047,2003-01-06 00:01:00,VANDALISM,"MALICIOUS MISCHIEF, VANDALISM OF VEHICLES",Monday,SOUTHERN,NONE,TOWNSEND ST / 2ND ST,-122.390531,37.780607,00:01:00,6,01,2003,MILD,MILD
878048,2003-01-06 00:01:00,FORGERY/COUNTERFEITING,"CHECKS, FORGERY (FELONY)",Monday,BAYVIEW,NONE,1800 Block of NEWCOMB AV,-122.394926,37.738212,00:01:00,6,01,2003,FORGERY/COUNTERFEITING,FORGERY/COUNTERFEITING